### ISSUE TITLE
Random number generator device

### ISSUE THREAD

**Issue by Vanuan** [libvirt/libvirt-go-xml#25]
It looks like there's no way to specify tpm or rng device. Without `/dev/urandom` linux would struggle to boot.

Something like this:

```
      Rngs:
       Model: virtio
       Backend:
          Model: random
          Value: /dev/urandom
```

should be transformed into this:

```
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
    </rng>
```
